# Generated by Django 4.2.7 on 2024-01-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="stats",
        ),
    ]
