# Generated by Django 4.2.7 on 2024-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_remove_player_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="assists_at",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="assists_ts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="developed_at",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="developed_ts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="games_at",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="games_ts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="goals_at",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="goals_ts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="injured_at",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="trained_at",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="trained_ts",
            field=models.IntegerField(default=0),
        ),
    ]
